### ISSUE TITLE
Examples don't represent actual implementation

### ISSUE THREAD

**Issue by ChxGuillaume** [gompocp/ActionMenuApi#5]
You may have changed the order of some parameters and the examples don't correspond anymore 😄

**Comment by gompocp** [comment]
And you'd be correct there 😅 (oops)
If it helps, I've added the documentation .xml file to the latest release [here](https://github.com/gompocp/ActionMenuApi/releases/download/v0.3.3/ActionMenuApi.xml) . Which you can place beside the .dll and your ide should pick up on it

**Comment by ChxGuillaume** [comment]
Yup that's all working well, using Rider it helps a lot 😋

**Comment by gompocp** [comment]
Sweet, glad to hear 👍
 (Rider ftw😄 )
